# frontend/Dockerfile

# Étape de build
FROM node:16 as build

WORKDIR /app

# Copier package.json et package-lock.json (ou yarn.lock)
COPY package.json package-lock.json ./
RUN npm install

# Copier tout le code source et construire l'application
COPY . .
RUN npm run build

# Étape de production avec Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]